import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { WagmiProvider } from 'wagmi'
import { wagmiConfig } from './config'
import { AppReactQueryProvider } from './providers'


import Navbar from "@/components/Navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">

      <ThemeProvider>
        <WagmiProvider config={wagmiConfig}>
          <AppReactQueryProvider>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <Navbar />
              {children}
            </body>
          </AppReactQueryProvider>
        </WagmiProvider>
      </ThemeProvider>
    </html>
  );
}
